/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import common.Utils;
import dao.StaffDao;
import java.time.LocalDate;
import java.util.List;
import model.Staff;


public class AddOrEditStaff extends javax.swing.JFrame {

    private int staffId;
    private StaffDao staffDao = StaffDao.getInstance();
    private ManageStaff parentView;

    /**
     * Creates new form Add_new_staff
     */
    public AddOrEditStaff(ManageStaff parentView) {
        this(-1, parentView);
    }

    public AddOrEditStaff(int staffId, ManageStaff parentView) {
        this.staffId = staffId;
        this.parentView = parentView;
        initComponents();
        validateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Monthly = new javax.swing.JLabel();
        End = new javax.swing.JLabel();
        Start = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cbxSex = new javax.swing.JComboBox<>();
        cbxPosition = new javax.swing.JComboBox<>();
        btnAction = new javax.swing.JButton();
        dpStart = new com.toedter.calendar.JDateChooser();
        dpBirthDate = new com.toedter.calendar.JDateChooser();
        dpEnd = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        btnAction1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(744, 573));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(255, 51, 51));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(240, 212, 167));
        lblTitle.setText("New Staff");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(153, 153, 153));
        Name.setText("Full Name");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 102, 30));

        Date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(153, 153, 153));
        Date.setText("Birth Date");
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 70, 30));

        Phone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Phone.setForeground(new java.awt.Color(153, 153, 153));
        Phone.setText("Phone Number");
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 255, -1, 20));

        Monthly.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Monthly.setForeground(new java.awt.Color(153, 153, 153));
        Monthly.setText("Monthly Salary");
        jPanel1.add(Monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 305, 102, 20));

        End.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        End.setForeground(new java.awt.Color(153, 153, 153));
        End.setText("End Date");
        jPanel1.add(End, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 70, 30));

        Start.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Start.setForeground(new java.awt.Color(153, 153, 153));
        Start.setText("Start Date");
        jPanel1.add(Start, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 70, 30));

        txtName.setBackground(new java.awt.Color(250, 242, 228));
        txtName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 299, 30));

        txtSalary.setBackground(new java.awt.Color(250, 242, 228));
        txtSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSalaryKeyReleased(evt);
            }
        });
        jPanel1.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 299, 30));

        txtPhone.setBackground(new java.awt.Color(250, 242, 228));
        txtPhone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 299, 30));

        cbxSex.setBackground(new java.awt.Color(250, 242, 228));
        cbxSex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxSex.setToolTipText("");
        cbxSex.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbxSex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSexActionPerformed(evt);
            }
        });
        jPanel1.add(cbxSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 100, 30));

        cbxPosition.setBackground(new java.awt.Color(250, 242, 228));
        cbxPosition.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cbxPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 299, 30));

        btnAction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAction.setForeground(new java.awt.Color(225, 169, 80));
        btnAction.setText("Save");
        btnAction.setBorderPainted(false);
        btnAction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAction.setEnabled(false);
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAction, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 100, 30));

        dpStart.setBackground(new java.awt.Color(250, 242, 228));
        dpStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpStart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpStartPropertyChange(evt);
            }
        });
        jPanel1.add(dpStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 140, 30));

        dpBirthDate.setBackground(new java.awt.Color(250, 242, 228));
        dpBirthDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpBirthDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpBirthDatePropertyChange(evt);
            }
        });
        jPanel1.add(dpBirthDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 180, 30));

        dpEnd.setBackground(new java.awt.Color(250, 242, 228));
        dpEnd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        dpEnd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpEndPropertyChange(evt);
            }
        });
        jPanel1.add(dpEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 140, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        btnAction1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAction1.setForeground(new java.awt.Color(225, 169, 80));
        btnAction1.setText("Clear");
        btnAction1.setBorderPainted(false);
        btnAction1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAction1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAction1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAction1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxSexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSexActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        List.of("Male", "Female").forEach(cbxSex::addItem);
        List.of("Barista", "Server", "Chef", "Manager", "Counter Service", "Shipper").forEach(cbxPosition::addItem);

        if (staffId != -1) {
            lblTitle.setText("Edit Staff");
            lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view edit delete product.png")));

            Staff staff = staffDao.getById(staffId);
            txtName.setText(staff.getFullName());
            cbxSex.setSelectedItem(staff.getSex());
            dpBirthDate.setDate(Utils.toDate(staff.getBirthDate()));
            txtPhone.setText(staff.getPhoneNumber());
            cbxPosition.setSelectedItem(staff.getPosition());
            txtSalary.setText("%.2f".formatted(staff.getMonthlySalary()));
            dpStart.setDate(Utils.toDate(staff.getStartDate()));
            dpEnd.setDate(Utils.toDate(staff.getEndDate()));
        } 
    }//GEN-LAST:event_formComponentShown

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        validateFields();
    }//GEN-LAST:event_txtNameKeyReleased

    private void dpBirthDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpBirthDatePropertyChange
        validateFields();
    }//GEN-LAST:event_dpBirthDatePropertyChange

    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
        validateFields();
    }//GEN-LAST:event_txtPhoneKeyReleased

    private void txtSalaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalaryKeyReleased
        validateFields();
    }//GEN-LAST:event_txtSalaryKeyReleased

    private void dpStartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpStartPropertyChange
        validateFields();
    }//GEN-LAST:event_dpStartPropertyChange

    private void dpEndPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpEndPropertyChange
        validateFields();
    }//GEN-LAST:event_dpEndPropertyChange

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        Staff staff = new Staff();
        staff.setFullName(txtName.getText());
        staff.setSex((String) cbxSex.getSelectedItem());
        staff.setBirthDate(Utils.toLocalDate(dpBirthDate.getDate()));
        staff.setPhoneNumber(txtPhone.getText());
        staff.setPosition((String) cbxPosition.getSelectedItem());
        staff.setMonthlySalary(Double.parseDouble(txtSalary.getText()));
        staff.setStartDate(Utils.toLocalDate(dpStart.getDate()));
        staff.setEndDate(Utils.toLocalDate(dpEnd.getDate()));

        if (staffId == -1) {
            staffDao.saveStaff(staff);
        } else {
            staff.setId(staffId);
            staffDao.updateStaff(staff);
        }
        setVisible(false);
        parentView.loadStaffList();
    }//GEN-LAST:event_btnActionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAction1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAction1ActionPerformed
        txtName.setText("");
        cbxSex.setSelectedIndex(0);
        dpBirthDate.setDate(null);
        txtPhone.setText("");
        cbxPosition.setSelectedIndex(0);
        txtSalary.setText("");
        dpStart.setDate(null);
        dpEnd.setDate(null);
        validateFields();
    }//GEN-LAST:event_btnAction1ActionPerformed

    private void validateFields() {
        LocalDate birthDate = Utils.toLocalDate(dpBirthDate.getDate());
        LocalDate startDate = Utils.toLocalDate(dpStart.getDate());
        LocalDate endDate = Utils.toLocalDate(dpEnd.getDate());
        try {
            double salary = Double.parseDouble(txtSalary.getText());
            if (!txtName.getText().isEmpty()
                    && birthDate != null && birthDate.isBefore(LocalDate.now())
                    && txtPhone.getText().matches("[0-9]{10}")
                    && salary > 0
                    && startDate != null
                    && (endDate == null || (!startDate.isAfter(endDate)))) {
                btnAction.setEnabled(true);
            } else {
                btnAction.setEnabled(false);
            }
        } catch (Exception ex) {
            btnAction.setEnabled(false);
        }
        if (txtName.getText().equals("")) {
            Name.setVisible(true);
        } else {
            Name.setVisible(false);
        }
        if (dpBirthDate.getDate() == null) {
            Date.setVisible(true);
        } else {
            Date.setVisible(false);
        }
        if (dpStart.getDate() == null) {
            Start.setVisible(true);
        } else {
            Start.setVisible(false);
        }
        if (dpEnd.getDate() == null) {
            End.setVisible(true);
        } else {
            End.setVisible(false);
        }
        if (txtPhone.getText().equals("")) {
            Phone.setVisible(true);
        } else {
            Phone.setVisible(false);
        }
        if (txtSalary.getText().equals("")) {
            Monthly.setVisible(true);
        } else {
            Monthly.setVisible(false);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrEditStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrEditStaff(1, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JLabel End;
    private javax.swing.JLabel Monthly;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel Start;
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnAction1;
    private javax.swing.JComboBox<String> cbxPosition;
    private javax.swing.JComboBox<String> cbxSex;
    private com.toedter.calendar.JDateChooser dpBirthDate;
    private com.toedter.calendar.JDateChooser dpEnd;
    private com.toedter.calendar.JDateChooser dpStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSalary;
    // End of variables declaration//GEN-END:variables
}
