/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.CartDao;
import dao.CategoryDao;
import dao.ProductDao;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cart;
import model.CartItem;
import model.Product;


public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    private int userId;
    private Cart cart;
    private List<Product> products;
    private List<Product> productsFilteredByCategory;
    private List<Product> productsSearched;

    public Menu(int userId) {
        this();
        this.userId = userId;
        cart = CartDao.getInstance().getCart(userId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        productList = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxCategory = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        chbxSortByPrice = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtUnitPrice = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        btnClearCart = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productList.setBackground(new java.awt.Color(250, 242, 228));
        productList.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        jScrollPane1.setViewportView(productList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 206, 798, 460));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 212, 167));
        jLabel1.setText("MENU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        txtSearch.setBackground(new java.awt.Color(250, 242, 228));
        txtSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 114, 207, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 212, 167));
        jLabel2.setText("Search:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 80, 30));

        cbxCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxCategory.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxCategoryItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 73, 207, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 212, 167));
        jLabel3.setText("Category:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        chbxSortByPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        chbxSortByPrice.setForeground(new java.awt.Color(240, 212, 167));
        chbxSortByPrice.setText("Sort by price");
        chbxSortByPrice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbxSortByPriceStateChanged(evt);
            }
        });
        chbxSortByPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxSortByPriceActionPerformed(evt);
            }
        });
        getContentPane().add(chbxSortByPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 154, 131, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(240, 212, 167));
        jRadioButton1.setText("ASC");
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 154, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(240, 212, 167));
        jRadioButton2.setText("DESC");
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 154, -1, -1));

        tblCart.setBackground(new java.awt.Color(250, 242, 228));
        tblCart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "ProductName", "Quantity", "Subtotal"
            }
        ));
        tblCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCartMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblCart);
        if (tblCart.getColumnModel().getColumnCount() > 0) {
            tblCart.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 73, 420, 260));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 212, 167));
        jLabel4.setText("CART");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, -1, -1));

        spnQuantity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spnQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityStateChanged(evt);
            }
        });
        getContentPane().add(spnQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, 231, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 212, 167));
        jLabel5.setText("Product Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 212, 167));
        jLabel6.setText("Unit price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 103, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 212, 167));
        jLabel7.setText("Quantity: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 103, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 212, 167));
        jLabel8.setText("Total: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 103, 30));

        txtProductName.setBackground(new java.awt.Color(250, 242, 228));
        txtProductName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 390, 231, -1));

        txtUnitPrice.setBackground(new java.awt.Color(250, 242, 228));
        txtUnitPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnitPrice.setForeground(new java.awt.Color(250, 242, 228));
        getContentPane().add(txtUnitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 430, 231, 27));

        txtTotal.setBackground(new java.awt.Color(250, 242, 228));
        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(250, 242, 228));
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 510, 231, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(225, 169, 80));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 560, 170, 40));

        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(225, 169, 80));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 560, 161, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 212, 167));
        jLabel9.setText("Total: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 340, 70, 26));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(240, 212, 167));
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTotal.setText("$ 0,00");
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 340, 96, -1));

        btnPlaceOrder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(225, 169, 80));
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        getContentPane().add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 610, 170, 40));

        btnClearCart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClearCart.setForeground(new java.awt.Color(225, 169, 80));
        btnClearCart.setText("Clear Cart");
        btnClearCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearCartActionPerformed(evt);
            }
        });
        getContentPane().add(btnClearCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 610, 161, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private CartItem findItemByProductName(String productName) {
        return cart.getItems().stream()
                .filter(item -> item.getProduct().getName().equals(productName))
                .toList().get(0);
    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        CartItem cartItem = findItemByProductName(txtProductName.getText());
        cartItem.setQuantity((Integer) spnQuantity.getValue());
        loadCart();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        products = ProductDao.getInstance().getAll();
        productsFilteredByCategory = products;
        productsSearched = products;
        products.stream()
                .map(product -> new ProductItem(product, cart, this))
                .forEach(productList::add);

        cbxCategory.addItem("All");
        CategoryDao.getInstance().getAllRecords().forEach(category -> {
            cbxCategory.addItem(category.getName());
        });

        loadCart();

        txtProductName.setEditable(false);
        txtUnitPrice.setEditable(false);
        txtTotal.setEditable(false);
        spnQuantity.setEnabled(false);
    }//GEN-LAST:event_formComponentShown

    private DefaultTableModel tableModel;

    void loadCart() {
        btnUpdate.setEnabled(false);
        btnRemove.setEnabled(false);
        
        txtProductName.setText("");
        txtUnitPrice.setText("");
        spnQuantity.setValue(0);
        spnQuantity.setEnabled(false);
        txtTotal.setText("");

        tableModel = (DefaultTableModel) tblCart.getModel();
        tableModel.setRowCount(0);
        cart.getItems().forEach(item -> {
            tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, item.getProduct().getName(), item.getQuantity(), "%.2f".formatted(item.getProduct().getPrice() * item.getQuantity())});
        });

        double total = cart.getItems().stream().mapToDouble(item -> item.getProduct().getPrice() * item.getQuantity()).sum();
        lblTotal.setText(String.format("$ %.2f", total));

        new Thread(() -> {
            CartDao.getInstance().clearCart(userId);
            CartDao.getInstance().saveCart(cart);
        }).start();

    }

    private void cbxCategoryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxCategoryItemStateChanged
        if (products == null) {
            return;
        }
        txtSearch.setText("");

        String selectedItem = (String) cbxCategory.getSelectedItem();
        if (selectedItem.equals("All")) {
            productList.removeAll();
            productsFilteredByCategory = products;
            productsSearched = products;

            productsFilteredByCategory.stream()
                    .map(product -> new ProductItem(product, cart, this))
                    .forEach(productList::add);
        } else {
            productList.removeAll();
            productsFilteredByCategory = products.stream()
                    .filter(product -> product.getCategory().getName().equals(selectedItem))
                    .toList();
            productsSearched = productsFilteredByCategory;

            productsFilteredByCategory.stream()
                    .map(product -> new ProductItem(product, cart, this))
                    .forEach(productList::add);
        }
    }//GEN-LAST:event_cbxCategoryItemStateChanged

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        productList.removeAll();
        chbxSortByPrice.setSelected(false);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);

        productsSearched = productsFilteredByCategory.stream()
                .filter(product -> product.getName().toLowerCase().contains(txtSearch.getText().toLowerCase()))
                .toList();
        productsSearched.stream()
                .map(product -> new ProductItem(product, cart, this))
                .forEach(productList::add);
        revalidate();
        repaint();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void chbxSortByPriceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbxSortByPriceStateChanged

    }//GEN-LAST:event_chbxSortByPriceStateChanged

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged
        if (jRadioButton1.isSelected()) {
            productList.removeAll();
            productsSearched.stream()
                    .sorted(Comparator.comparingDouble(Product::getPrice))
                    .map(product -> new ProductItem(product, cart, this))
                    .forEach(productList::add);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged
        if (jRadioButton2.isSelected()) {
            productList.removeAll();
            productsSearched.stream()
                    .sorted((o1, o2) -> Double.valueOf(o2.getPrice()).compareTo(Double.valueOf(o1.getPrice())))
                    .map(product -> new ProductItem(product, cart, this))
                    .forEach(productList::add);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_jRadioButton2StateChanged

    private void chbxSortByPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxSortByPriceActionPerformed
        if (chbxSortByPrice.isSelected()) {
            jRadioButton1.setVisible(true);
            jRadioButton2.setVisible(true);
            jRadioButton1.setSelected(true);
        } else {
            jRadioButton1.setVisible(false);
            jRadioButton2.setVisible(false);
            productList.removeAll();
            productsSearched.stream()
                    .map(product -> new ProductItem(product, cart, this))
                    .forEach(productList::add);
        }
    }//GEN-LAST:event_chbxSortByPriceActionPerformed

    private void tblCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCartMouseClicked

        var cartItem = cart.getItems().stream()
                .filter(item -> item.getProduct().getName().equals(tableModel.getValueAt(tblCart.getSelectedRow(), 1)))
                .toList().get(0);
        txtProductName.setText(cartItem.getProduct().getName());
        txtUnitPrice.setText("%.2f".formatted(cartItem.getProduct().getPrice()));
        spnQuantity.setEnabled(true);
        spnQuantity.setValue(cartItem.getQuantity());

        btnUpdate.setEnabled(true);
        btnRemove.setEnabled(true);
    }//GEN-LAST:event_tblCartMouseClicked

    private void spnQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityStateChanged
        if (txtUnitPrice.getText().isEmpty()) {
            return;
        }
        txtTotal.setText("%.2f".formatted(Double.parseDouble(txtUnitPrice.getText()) * ((Integer) spnQuantity.getValue())));
    }//GEN-LAST:event_spnQuantityStateChanged

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        cart.getItems().remove(findItemByProductName(txtProductName.getText()));
        loadCart();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnClearCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearCartActionPerformed
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to clear all products in your cart?");
        if (ans == JOptionPane.YES_OPTION) {
            cart.getItems().clear();
            loadCart();
        }
    }//GEN-LAST:event_btnClearCartActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        if (cart.getItems().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Your cart is empty!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        new PlaceOrderView(userId, cart, this).setVisible(true);
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearCart;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JCheckBox chbxSortByPrice;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel productList;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUnitPrice;
    // End of variables declaration//GEN-END:variables
}
