/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import common.Utils;
import dao.OrderDao;
import dao.StaffDao;
import java.awt.Component;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.table.DefaultTableModel;
import model.Order;
import model.Staff;
import model.Status;



public class ViewOrManageOrders extends javax.swing.JFrame {

    /**
     * Creates new form ManageOrder
     */
    public ViewOrManageOrders() {
        this(-1);
    }

    public ViewOrManageOrders(int userId) {
        initComponents();
        this.userId = userId;
    }

    private int userId;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        cbxShipper = new javax.swing.JComboBox<>();
        cbxStatus = new javax.swing.JComboBox<>();
        btnUpdate = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dpTo = new com.toedter.calendar.JDateChooser();
        lblShipper = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dpFrom = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrders.setBackground(new java.awt.Color(250, 242, 228));
        tblOrders.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Created at", "User email", "Total", "Shipper", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);
        if (tblOrders.getColumnModel().getColumnCount() > 0) {
            tblOrders.getColumnModel().getColumn(0).setMinWidth(100);
            tblOrders.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblOrders.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 94, 1100, 390));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 212, 167));
        jLabel1.setText("To");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, -1));

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(240, 212, 167));
        lblStatus.setText("Change status");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, -1, -1));

        cbxShipper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cbxShipper, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 560, 182, -1));

        cbxStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jPanel1.add(cbxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 182, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(225, 169, 80));
        btnUpdate.setText("Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 144, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 212, 167));
        jLabel3.setText("Manage Order");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        dpTo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpToPropertyChange(evt);
            }
        });
        jPanel1.add(dpTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, 200, -1));

        lblShipper.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblShipper.setForeground(new java.awt.Color(240, 212, 167));
        lblShipper.setText("Set shipper");
        jPanel1.add(lblShipper, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 212, 167));
        jLabel6.setText("From");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        dpFrom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpFromPropertyChange(evt);
            }
        });
        jPanel1.add(dpFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 200, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, -1, -1));

        btnDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDetails.setForeground(new java.awt.Color(225, 169, 80));
        btnDetails.setText("View Details");
        btnDetails.setBorderPainted(false);
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        jPanel1.add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 144, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    List<Status> statusList;

    List<Staff> shipperList;

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown

        cbxShipper.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Staff staff) {
                    if (staff.getId() == 0) {
                        setText("None");
                    } else {
                        setText(staff.getFullName() + " (ID: " + staff.getId() + ")");
                    }
                }
                return this;
            }

        });

        Staff staff = new Staff();
        staff.setId(0);
        cbxShipper.addItem(staff);
        shipperList = StaffDao.getInstance().getShippers();
        shipperList.forEach(cbxShipper::addItem);

        cbxStatus.setRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Status status) {
                    setText(status.getValue());
                }
                return this;
            }

        });
        statusList = OrderDao.getInstance().getAllStatus();
        statusList.forEach((status) -> {
            cbxStatus.addItem(status);
        });

        loadOrders();
    }//GEN-LAST:event_formComponentShown

    private void dpFromPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpFromPropertyChange
        loadOrders();
    }//GEN-LAST:event_dpFromPropertyChange

    private void dpToPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpToPropertyChange
        loadOrders();
    }//GEN-LAST:event_dpToPropertyChange

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked

        btnDetails.setVisible(true);

        if (userId == -1) {
            String status = (String) tblOrders.getValueAt(tblOrders.getSelectedRow(), 5);
            cbxStatus.setSelectedItem(statusList.stream().filter(s -> s.getValue().equals(status)).findFirst().get());

            String shipper = (String) tblOrders.getValueAt(tblOrders.getSelectedRow(), 4);
            if (shipper.equals("(Not yet assigned)")) {
                cbxShipper.setSelectedIndex(0);
            } else {
                cbxShipper.setSelectedItem(shipperList.stream().filter(s -> (s.getFullName() + " (ID: " + s.getId() + ")").equals(shipper)).findFirst().get());
            }

            lblShipper.setVisible(true);
            lblStatus.setVisible(true);
            cbxShipper.setVisible(true);
            cbxStatus.setVisible(true);
            btnUpdate.setVisible(true);
        }
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Order order = new Order();
        order.setId((Integer) tblOrders.getValueAt(tblOrders.getSelectedRow(), 0));
        if (((Staff) cbxShipper.getSelectedItem()).getId() != 0) {
            order.setShipper((Staff) cbxShipper.getSelectedItem());
        }
        order.setStatus((Status) cbxStatus.getSelectedItem());
        OrderDao.getInstance().updateOrder(order);
        loadOrders();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int id = (Integer) tblOrders.getValueAt(tblOrders.getSelectedRow(), 0);
        new ViewOrderDetails(id).setVisible(true);
    }//GEN-LAST:event_btnDetailsActionPerformed

    private void loadOrders() {

        btnDetails.setVisible(false);
        lblShipper.setVisible(false);
        lblStatus.setVisible(false);
        cbxShipper.setVisible(false);
        cbxStatus.setVisible(false);
        btnUpdate.setVisible(false);

        DefaultTableModel tableModel = (DefaultTableModel) tblOrders.getModel();
        tableModel.setRowCount(0);

        OrderDao.getInstance().getOrders(userId, Utils.toLocalDate(dpFrom.getDate()), Utils.toLocalDate(dpTo.getDate()))
                .forEach(order -> tableModel.addRow(new Object[]{
            order.getId(),
            order.getCreatedAt().format(DateTimeFormatter.ofPattern("yyyy-MM-dd hh:mm")),
            order.getUser().getEmail(),
            order.getFinalCost(),
            order.getShipper() == null ? "(Not yet assigned)" : order.getShipper().getFullName() + " (ID: " + order.getShipper().getId() + ")",
            order.getStatus().getValue()
        }));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOrManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOrManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOrManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOrManageOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOrManageOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<Staff> cbxShipper;
    private javax.swing.JComboBox<Status> cbxStatus;
    private com.toedter.calendar.JDateChooser dpFrom;
    private com.toedter.calendar.JDateChooser dpTo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblShipper;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTable tblOrders;
    // End of variables declaration//GEN-END:variables
}
